{% set version = "1.2.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-openimager
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/OpenImageR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/OpenImageR/OpenImageR_{{ version }}.tar.gz
  sha256: eaad6d6e5b567facb2b87f8a327cb18baba95ef0acee5f48770433056be74872

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-rcpp >=0.12.17
    - r-rcpparmadillo >=0.8.0
    - r-jpeg
    - r-png
    - r-shiny
    - r-tiff
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-r6
    - r-rcpp >=0.12.17
    - r-rcpparmadillo >=0.8.0
    - r-jpeg
    - r-png
    - r-shiny
    - r-tiff

test:
  commands:
    - $R -e "library('OpenImageR')"           # [not win]
    - "\"%R%\" -e \"library('OpenImageR')\""  # [win]

about:
  home: https://github.com/mlampros/OpenImageR
  license: GPL-3.0-only
  summary: "Incorporates functions for image preprocessing, filtering and image recognition. The package takes advantage of 'RcppArmadillo' to speed up computationally intensive functions. The histogram of oriented gradients descriptor is a modification of the 'findHOGFeatures' function of the 'SimpleCV' computer vision\
    \ platform, the average_hash(), dhash() and phash() functions are based on the 'ImageHash' python library. The Gabor Feature Extraction functions are based on 'Matlab' code of the paper, \"CloudID: Trustworthy cloud-based and cross-enterprise biometric identification\" by M. Haghighat, S. Zonouz, M. Abdel-Mottaleb, Expert\
    \ Systems with Applications, vol. 42, no. 21, pp. 7905-7916, 2015, <doi:10.1016/j.eswa.2015.06.025>. The 'SLIC' and 'SLICO' superpixel algorithms were explained in detail in (i) \"SLIC Superpixels Compared to State-of-the-art Superpixel Methods\", Radhakrishna Achanta, Appu Shaji, Kevin Smith, Aurelien Lucchi, Pascal\
    \ Fua, and Sabine Suesstrunk, IEEE Transactions on Pattern Analysis and Machine Intelligence, vol. 34, num. 11, p. 2274-2282, May 2012, <doi:10.1109/TPAMI.2012.120> and (ii) \"SLIC Superpixels\", Radhakrishna Achanta, Appu Shaji, Kevin Smith, Aurelien Lucchi, Pascal Fua, and Sabine Suesstrunk, EPFL Technical Report no.\
    \ 149300, June 2010."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: OpenImageR
# Type: Package
# Title: An Image Processing Toolkit
# Version: 1.1.5
# Date: 2019-02-10
# Depends: R(>= 3.2.3)
# Imports: Rcpp (>= 0.12.17), shiny, jpeg, png, tiff, utils, R6
# Authors@R: c( person("Lampros", "Mouselimis", email = "mouselimislampros@gmail.com", role = c("aut", "cre")), person("Sight", "Machine", role = "cph", comment = "findHOGFeatures function of the SimpleCV computer vision platform"), person("Johannes", "Buchner", role = "cph", comment = "average_hash, dhash and phash functions of the ImageHash python library"), person("Mohammad", "Haghighat", email = "haghighat@ieee.org", role = "cph", comment = "Gabor Feature Extraction"), person("Radhakrishna", "Achanta", email = "Radhakrishna.Achanta@epfl.ch", role = "cph", comment = "Author of the C++ code of the SLIC and SLICO algorithms (for commercial use please contact the author)") )
# Maintainer: Lampros Mouselimis <mouselimislampros@gmail.com>
# BugReports: https://github.com/mlampros/OpenImageR/issues
# URL: https://github.com/mlampros/OpenImageR
# Description: Incorporates functions for image preprocessing, filtering and image recognition. The package takes advantage of 'RcppArmadillo' to speed up computationally intensive functions. The histogram of oriented gradients descriptor is a modification of the 'findHOGFeatures' function of the 'SimpleCV' computer vision platform, the average_hash(), dhash() and phash() functions are based on the 'ImageHash' python library. The Gabor Feature Extraction functions are based on 'Matlab' code of the paper, "CloudID: Trustworthy cloud-based and cross-enterprise biometric identification" by M. Haghighat, S. Zonouz, M. Abdel-Mottaleb, Expert Systems with Applications, vol. 42, no. 21, pp. 7905-7916, 2015, <doi:10.1016/j.eswa.2015.06.025>. The 'SLIC' and 'SLICO' superpixel algorithms were explained in detail in (i) "SLIC Superpixels Compared to State-of-the-art Superpixel Methods", Radhakrishna Achanta, Appu Shaji, Kevin Smith, Aurelien Lucchi, Pascal Fua, and Sabine Suesstrunk, IEEE Transactions on Pattern Analysis and Machine Intelligence, vol. 34, num. 11, p. 2274-2282, May 2012, <doi:10.1109/TPAMI.2012.120> and (ii) "SLIC Superpixels", Radhakrishna Achanta, Appu Shaji, Kevin Smith, Aurelien Lucchi, Pascal Fua, and Sabine Suesstrunk, EPFL Technical Report no. 149300, June 2010.
# License: GPL-3
# Copyright: inst/COPYRIGHTS
# SystemRequirements: The package requires a C++11 compiler.
# LinkingTo: Rcpp, RcppArmadillo (>= 0.8.0)
# Suggests: testthat, knitr, rmarkdown, grid, covr
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-02-10 07:27:46 UTC; lampros
# Author: Lampros Mouselimis [aut, cre], Sight Machine [cph] (findHOGFeatures function of the SimpleCV computer vision platform), Johannes Buchner [cph] (average_hash, dhash and phash functions of the ImageHash python library), Mohammad Haghighat [cph] (Gabor Feature Extraction), Radhakrishna Achanta [cph] (Author of the C++ code of the SLIC and SLICO algorithms (for commercial use please contact the author))
# Repository: CRAN
# Date/Publication: 2019-02-10 08:03:13 UTC
