appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: nBkKn+nnrvFjXmKGjiWchJUskQa0gXqax6QBS1G8CoG16mCBtUKx5s4kdyIUGKGfLMjwLD5O7Y7CmkTHc068/q/HMKqZ6hYf9wWJZMPJ3Y43M19adNmtsEkbVSuFvwgjMjSyxPH9TBzo2cesXIoJKzxeFWjCQ8O1fmTK9ELp3GF1MfCuRVecShGrH0z67fnu73riuR/Tk6LD1W4l1wD26luz6G8WLSun1uG8o5kFmprahtzLBwe93Sv7iuD1o0j6vtdpA00esg9wB71N1LYK6ykxk4XDyV/tpIz1oO7nkGbvXOD98H6fLuQoJifcUPBR8JLudGoSb4tUocZtfXLeXpG34pgpogOcjSUgTsamDQv2K9d3usGzhCCDGorBp/QRKJdnMLsZY3HN4gAmfpXEQb0X2ryqHIDSAJ3K3SNEd2fEf5ILYLl7DnOSseCTDKsDW4EX7pNX8rlaEifBlJGpXvqlA37AcIxjZAjBrI51PJBYbcNNPUWwXoTW+IUbJylGW0dmXw0YV48qWnK6Tn8+T4i0V+a1L01CfhCsYxCXbbAMuQ8vxtETPP2smob+YJ+RzqeBzYR/0RMTCqUzIeBrKaZ5uGTIoP60W9L74vy/LR0LwuhDP+jI6MtjWpJgm4yGp/Fg+ZdJxLfauS3S3es9Qi34jc5mPeO9I0YJwhgmUo4=
conda_forge_output_validation: true
